version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions-updates:
        patterns:
          - "**"
  - package-ecosystem: npm
    directory: "/**"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
