idp:
  entity_id: http://mock-idp
  base_url: http://laa-ccms-caab-saml-mock.apps.live.cloud-platform.service.justice.gov.uk
  # SAML configuration file. To use an external file, prefix path with "file:".
  saml_attributes_config_file: classpath:saml-attributes.json
  # Private key used to sign the SAML response
  private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDQRsCf6qU0DYkoFIJUhNlMxJFKMPsEvK+u3rcaBIZcyWX4Cv5OU3xtcCAg6mqRwMRFYFDNdGgR0XLTaHAOcJpR7cXYnYc0Wa6Kh8KSstgZrCl+WdqCtuUS6bMrrAdSq6HpoAPwo1JyOqyC9ccRZ9ysjhYdWQS1ELSjUHjEuxxRoEgwKfrF7kxbo89dixQ7oF9E9CgeWtftJfMtDxGtMhmtaIurHjjcfOPWR8TND0b1Lp1pLkzPn6GdI2aRWqV3tNsljKoXP9omDInhP9xrzoLiXISbekfnLrfFQW+rmylCBiu6ZqKv0weg1V6b7B6rAyV3nIcXInLuKXSlQx0nnPOdAgMBAAECggEAOrAlKSqyYIeL5XpZ+zzwCly9X/2LThtpGcpyJ+esgMrTa+CVJjcKMcBNnVjQrL93zuDEBBDQHm05gO7F3JvIMFviyxYgehTnROvaXQH+OMW1b4AcPYcR55Foxl6UNaxdVHqdgZpT6hI0eDaPYI02tnzXKG/kDq1laTuMvErJQQp6Cd611yyAhBvpX1ibpAYvex10sfTkj0GRKmOrGqwVXibN29szaRei7Xeg/RStdVBgrYJoR5/4++dkGapa27oRdOh4VJUChRfXuJtH6pyxC7uay1fMRcmo2u6NcWAT6qMOvxLcuesnNFrbSlPoZaxWNiZRX/SVqeieyRAA0WS7IQKBgQDoywh4DkdL+SPrkA/sB0rOQF3kJjlzWibk9OM17In1P+obQk37kSRYKfBvsk48VWdG1fN33Up05Pxe+f36F//AZ8mp7uTmBtd6CAoR/005WxwkCSihF6LaDiB3VtxlpcfRA/TUZ10PMud43w0AeG30AG0KpCokfIiY87OpyTjJWQKBgQDlCgsgZ9rL3Wm7FbEDZ4f2uTB5rlT0Vz80paV0OOJdUQECrZW1PjemQpqIJocr8yoNupkrZKPSi4mbNoMFF1wXIydOjLq6iQ6KWIKRdsvmeXL++tWg6TiD8nDpBxuKzjRhwMcQN2lakb/SusoXnmG8qq12PCFUvpbhoZRqRPWv5QKBgQC8jUasxxPka0U21RawXC+w4t2pn3RFBC4goGEwGgibxkr+DTRQoHzJlB6Uud04bQwbicuLuIdIKvhmjSGzYaDa3LWwmDh6P+xjgQN3FEweOreOUITCBfz3lR2iy430HtS7bPLu31G2r8pgUnmbee/FBFtNlS41I1EYYbuRt9Pw8QKBgD6aPSpRWKtqTHD3X9e3X6FfQtGvhcb3Ze5E7HFU7wJklqsduRK9+8X05HocVcv8fd0cyKrkqiZtP2JuRueIWAJ2+FJvAsbjmVbVFHMgDmFjhrwM4YFG3cyq4pO+/pc0/3pMj9xt2N0Jg23c4koMX1iLKjhr/QxFv8XSPVfCm4jFAoGALfejdx4PpFgTWpbm5ZWRxukhZRhmfCIAWifYeJbsGTB5y7bheVxKmTpP9mKEqGL+gh3cLVPcZ557HWpc4d6NetdyrHffEhWULh4NWYDKC5BRCr9HjLKydBUQUMCFeJs3XZQTtN+CZORcuaI2ISH2QvfYki9ns4ujeH8OjzfHpvI=
  # Public certificate to verify the signature of the SAML response
  certificate: MIIDEzCCAfugAwIBAgIJAKoK/heBjcOYMA0GCSqGSIb3DQEBBQUAMCAxHjAcBgNVBAoMFU9yZ2FuaXphdGlvbiwgQ049T0lEQzAeFw0xNTExMTExMDEyMTVaFw0yNTExMTAxMDEyMTVaMCAxHjAcBgNVBAoMFU9yZ2FuaXphdGlvbiwgQ049T0lEQzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANBGwJ/qpTQNiSgUglSE2UzEkUow+wS8r67etxoEhlzJZfgK/k5TfG1wICDqapHAxEVgUM10aBHRctNocA5wmlHtxdidhzRZroqHwpKy2BmsKX5Z2oK25RLpsyusB1KroemgA/CjUnI6rIL1xxFn3KyOFh1ZBLUQtKNQeMS7HFGgSDAp+sXuTFujz12LFDugX0T0KB5a1+0l8y0PEa0yGa1oi6seONx849ZHxM0PRvUunWkuTM+foZ0jZpFapXe02yWMqhc/2iYMieE/3GvOguJchJt6R+cut8VBb6ubKUIGK7pmoq/TB6DVXpvsHqsDJXechxcicu4pdKVDHSec850CAwEAAaNQME4wHQYDVR0OBBYEFK7RqjoodSYVXGTVEdLf3kJflP/sMB8GA1UdIwQYMBaAFK7RqjoodSYVXGTVEdLf3kJflP/sMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBADNZkxlFXh4F45muCbnQd+WmaXlGvb9tkUyAIxVL8AIu8J18F420vpnGpoUAE+Hy3evBmp2nkrFAgmr055fAjpHeZFgDZBAPCwYd3TNMDeSyMta3Ka+oS7GRFDePkMEm+kH4/rITNKUF1sOvWBTSowk9TudEDyFqgGntcdu/l/zRxvx33y3LMG5USD0x4X4IKjRrRN1BbcKgi8dq10C3jdqNancTuPoqT3WWzRvVtB/q34B7F74/6JzgEoOCEHufBMp4ZFu54P0yEGtWfTwTzuoZobrChVVBt4w/XZagrRtUCDNwRpHNbpjxYudbqLqpi1MQpV9oht/BpTHVJG2i0ro=
  # Passphrase of the keystore
  passphrase: secret
  # The number of seconds before a lower time bound, or after an upper time bound, to consider still acceptable
  clock_skew: 300
  # Number of seconds after a message issue instant after which the message is considered expired
  expires: 300
  # Authentication method ALL for every username / password combination and USER for the configured users
  auth_method: ALL
  # Are endpoints compared. If so then pay notice to the base_url when behind a load balancer
  compare_endpoints: true
  attributes:
    [urn:mace:dir:attribute-def:uid]: "john.doe"
    [urn:mace:dir:attribute-def:cn]: "John Doe"
    [urn:mace:dir:attribute-def:givenName]: "John"
    [urn:mace:dir:attribute-def:sn]: "Doe"
    [urn:mace:dir:attribute-def:displayName]: "John Doe"
    [urn:mace:dir:attribute-def:mail]: "j.doe@example.com"
    [urn:mace:terena.org:attribute-def:schacHomeOrganization]: "example.com"
    [urn:mace:dir:attribute-def:eduPersonPrincipalName]: "j.doe@example.com"

secure_cookie: false

samlUserStore:
  samlUsers:
    - username: MARILYN@DESORANDCO.CO.UK
      password: test password
      samlAttributes:
        LAA_ACCOUNTS: 12345
        LAA_APP_ROLES: CCR_CCRAdministrator,CCR_CCRDirector,CCLF_BillManager,CCLF_NCTCaseworker,CCLF_BillAuthoriser
    - username: ABRA-S
      password: <IDP_PASSWORD_2>
      samlAttributes:
        LAA_ACCOUNTS: 12345
        LAA_APP_ROLES: CCR_CCRGradeA1,CCLF_SeniorBillAuthoriser
    - username: laauser
      password: <IDP_PASSWORD_3>
      samlAttributes:
        LAA_ACCOUNTS: 12345
        LAA_APP_ROLES: CCR_CCRGradeA1
    - username: MARILYN@DESORANDCO.CO.UK
      password: test password
      samlAttributes:
        LAA_ACCOUNTS: 0N003X:0N290J:0N757R:2M981Y:2M982Z:2N414U
        LAA_APP_ROLES: EFORMS,EFORMS_eFormsReviewer,PUI_XXCCMS_BILL_PREPARATION,PUI,PUI_XXCCMS_CASE_MANAGEMENT,PUI_XXCCMS_BILL_SUPERVISOR2,CCMS_Apply,PUI_XXCCMS_CASE_MGT_SUPERVISOR,EFORMS_eFormsAuthor
    - username: JULIEL@DUNCANLEWIS.COM
      password: testpassword
      samlAttributes:
        LAA_ACCOUNTS: 12345
        LAA_APP_ROLES: CCR_CCRAdministrator,CCR_CCRDirector,CCLF_BillManager,CCLF_NCTCaseworker,CCLF_BillAuthoriser
    - username: PENNY.WALL@SWITALSKIS.COM
      password: test password
      samlAttributes:
        LAA_ACCOUNTS: 0N003X:0N290J:0N757R:2M981Y:2M982Z:2N414U
        LAA_APP_ROLES: EFORMS,EFORMS_eFormsReviewer,PUI_XXCCMS_BILL_PREPARATION,PUI,PUI_XXCCMS_CASE_MANAGEMENT,PUI_XXCCMS_BILL_SUPERVISOR2,CCMS_Apply,PUI_XXCCMS_CASE_MGT_SUPERVISOR,EFORMS_eFormsAuthor
